<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Climaenergo - Продажа и сервис кондиционеров</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <div class="container">
            <h1>Climaenergo</h1>
            <p>Продажа и сервис кондиционеров и сплит-систем</p>
        </div>
    </header>

    <nav>
        <div class="container">
            <ul>
                <li><a href="#about">О нас</a></li>
                <li><a href="#services">Услуги</a></li>
                <li><a href="#contact">Контакты</a></li>
            </ul>
        </div>
    </nav>

    <section id="about">
        <div class="container">
            <h2>О нас</h2>
            <p>Компания "Climaenergo" специализируется на продаже и обслуживании кондиционеров и сплит-систем. Мы предлагаем широкий выбор оборудования от ведущих производителей, а также профессиональный сервис и установку.</p>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <h2>Наши услуги</h2>
            <ul>
                <li>Продажа кондиционеров и сплит-систем</li>
                <li>Установка и монтаж</li>
                <li>Обслуживание и ремонт</li>
                <li>Консультации по выбору оборудования</li>
            </ul>
        </div>
    </section>

    <section id="contact">
        <div class="container">
            <h2>Контакты</h2>
            <div class="contact-card">
                <h3>Николаев Андрей Валерьевич</h3>
                "<p>Телефон: <a href="tel:+79260445070">+7 926 044-50-70</a></p>"
                "<p>Email: <a href="mailto:climaenergo@mail.ru">climaenergo@mail.ru</a></p>"
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <p>&copy; 2023 Climaenergo. Все права защищены.</p>
        </div>
    </footer>

    <script src="script.js"></script>
</body>
</html>
